// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiW5CnjJAlNSSKG2zai2gyIJisRAIykAk',
    appId: '1:284261755075:web:cdca37baf532ce94f8da76',
    messagingSenderId: '284261755075',
    projectId: 'flutter-chat-app-243ce',
    authDomain: 'flutter-chat-app-243ce.firebaseapp.com',
    storageBucket: 'flutter-chat-app-243ce.appspot.com',
    measurementId: 'G-P4K8GCQ262',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe72ytDdSji7aLGcOHXsN6oiIQigwPDEg',
    appId: '1:284261755075:android:b5fed508f5c0bdabf8da76',
    messagingSenderId: '284261755075',
    projectId: 'flutter-chat-app-243ce',
    storageBucket: 'flutter-chat-app-243ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDakEmNIvyvnzY7o9sWJkSBI6FpQbZ_Qiw',
    appId: '1:284261755075:ios:46ef20fc624d9182f8da76',
    messagingSenderId: '284261755075',
    projectId: 'flutter-chat-app-243ce',
    storageBucket: 'flutter-chat-app-243ce.appspot.com',
    iosClientId: '284261755075-kk26e79q90petbrrk5vblpupe4dtltpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDakEmNIvyvnzY7o9sWJkSBI6FpQbZ_Qiw',
    appId: '1:284261755075:ios:46ef20fc624d9182f8da76',
    messagingSenderId: '284261755075',
    projectId: 'flutter-chat-app-243ce',
    storageBucket: 'flutter-chat-app-243ce.appspot.com',
    iosClientId: '284261755075-kk26e79q90petbrrk5vblpupe4dtltpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseChatApp',
  );
}
